[project]
name = "twitter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "tweepy>=4.16.0",
    "pydantic>=2.8.0",
    "pytest>=8.3.0",
]

[tool.uv]
dev-dependencies = []
